source 'https://rubygems.org'
gem 'rails', '4.2.5.1' #update with the current version of your Rails
gem 'pg'
#gem 'postgresql'
gem 'rails-footnotes'
gem 'tzinfo-data'
gem 'hirb'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'rename'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
group :test, :development do
  gem 'rspec-rails'
  gem 'database_cleaner'
end
group :test do
  gem 'capybara'
end